### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by Juan-aga** [Juan-aga/Minishell#4]
- [ ] Display a prompt when waiting for a new command.

**Comment by Juan-aga** [comment]
The prompt is implemented.
At the moment it show the username and $.
If there's no enviroment it show guest and $.

**Comment by Juan-aga** [comment]
The prompt now shows the name of the program and the actual directory .
Show too $> at the end. It is green of the last exit_staus is 0, else it's red.

**Comment by emartinez-dev** [comment]
Hi Juan! I am having some problems interpreting single and double quotes because the prompt does something strange. When I am writing a command like > `echo "it works"`, the last quote advances to the start of the prompt and starts overwriting it. 

I tried commenting the prompt and creating a simpler one and its working fine now, so there is no hurry to fix the problem, as it could also be because of Linux / MacOS difference. I will attach some videos of the problem so you can see:

![captura minishell](https://user-images.githubusercontent.com/73340871/220568190-4c58d8da-2793-4d6d-81d1-8410f02d2cb2.gif)

![captura minishell2](https://user-images.githubusercontent.com/73340871/220568207-60aed848-3fef-4e44-b6d2-68128ed6ebcb.gif)

**Comment by Juan-aga** [comment]
Hi!!
Now i'm in the 42 Campus, it work's well here.
Is some problem with the readline function (in linux and somtimes it happens in MAC too). It allows a number of space to write, if you put more, it returns to the start of the line. But when you press enter, it recives well the complete line.
It's only a visual problem, but if you want, i can implement the prompt with get next line.

**Comment by emartinez-dev** [comment]
Oh great then! Don't worry, we leave it like this and I will only change it locally, thanks @Juan-aga !
